/*
 * Forca.java
 *
 * Created on September 18, 2007, 6:07 PM
 */

package br.org.codeforlife.exemplo.jogo.forca;

/**
 *
 * @author  diego
 */
public class Forca extends javax.swing.JPanel {
    
    /** Creates new form Forca */
    public Forca() {
        initComponents();
    }

    public javax.swing.JLabel getJLabelBracoDireito() {
        return jLabelBracoDireito;
    }

    public javax.swing.JLabel getJLabelBracoEsquerdo() {
        return jLabelBracoEsquerdo;
    }

    public javax.swing.JLabel getJLabelCabeca() {
        return jLabelCabeca;
    }

    public javax.swing.JLabel getJLabelCintura() {
        return jLabelCintura;
    }

    public javax.swing.JLabel getJLabelPernaDireita() {
        return jLabelPernaDireita;
    }

    public javax.swing.JLabel getJLabelPernaEsquerda() {
        return jLabelPernaEsquerda;
    }

    public javax.swing.JLabel getJLabelTronco() {
        return jLabelTronco;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabelCabeca = new javax.swing.JLabel();
        jLabelTronco = new javax.swing.JLabel();
        jLabelBracoEsquerdo = new javax.swing.JLabel();
        jLabelBracoDireito = new javax.swing.JLabel();
        jLabelCintura = new javax.swing.JLabel();
        jLabelPernaDireita = new javax.swing.JLabel();
        jLabelPernaEsquerda = new javax.swing.JLabel();

        setLayout(new java.awt.GridBagLayout());

        jLabelCabeca.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        add(jLabelCabeca, gridBagConstraints);

        jLabelTronco.setText("|");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        add(jLabelTronco, gridBagConstraints);

        jLabelBracoEsquerdo.setText("/");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        add(jLabelBracoEsquerdo, gridBagConstraints);

        jLabelBracoDireito.setText("\\");
            gridBagConstraints = new java.awt.GridBagConstraints();
            gridBagConstraints.gridx = 3;
            gridBagConstraints.gridy = 2;
            add(jLabelBracoDireito, gridBagConstraints);

            jLabelCintura.setText("|");
            gridBagConstraints = new java.awt.GridBagConstraints();
            gridBagConstraints.gridx = 2;
            gridBagConstraints.gridy = 3;
            add(jLabelCintura, gridBagConstraints);

            jLabelPernaDireita.setText("\\");
                gridBagConstraints = new java.awt.GridBagConstraints();
                gridBagConstraints.gridx = 3;
                gridBagConstraints.gridy = 4;
                add(jLabelPernaDireita, gridBagConstraints);

                jLabelPernaEsquerda.setText("/");
                gridBagConstraints = new java.awt.GridBagConstraints();
                gridBagConstraints.gridx = 1;
                gridBagConstraints.gridy = 4;
                add(jLabelPernaEsquerda, gridBagConstraints);
            }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelBracoDireito;
    private javax.swing.JLabel jLabelBracoEsquerdo;
    private javax.swing.JLabel jLabelCabeca;
    private javax.swing.JLabel jLabelCintura;
    private javax.swing.JLabel jLabelPernaDireita;
    private javax.swing.JLabel jLabelPernaEsquerda;
    private javax.swing.JLabel jLabelTronco;
    // End of variables declaration//GEN-END:variables
    
}
