algoritmo "L1Q6"
// Função :  aloca uma variavel do tipo inteiro, atribui um valor para a variavel
//			 e imprime ela na tela do computador
// Autor :  DIEGO PASSOS COSTA
// Data : 08/05/2012
//6.) Declare uma variável de nome, numero do tipo 
//inteiro, atribua a ele o valor 3, por fim faça o 
//programa imprimir na tela o conteúdo da variável de nome numero.
var
   numero : inteiro
inicio
      numero <- 5
      escreva(numero)
fimalgoritmo