algoritmo "L1Q11"
// Função :
// Autor :  SENAI
// Data : 08/05/2012
//11.)	Faça primeiro o computador perguntar a idade do usuário
//    e por fim o computador deve imprimir na tela a seguinte frase:
//    sua idade é <idade informada pelo usuário>
//Seção de Declarações
var
   idade_do_usuario: inteiro
inicio
      escreva("informe a sua idade: ")
      leia(idade_do_usuario)
      escreva("sua idade é: ", idade_do_usuario)
fimalgoritmo
