algoritmo "L1Q10"
// Função :
// Autor :  SENAI
// Data : 08/05/2012
//10.)	Faça primeiro com que o computador pergunte o nome do usuário,
//    depois o usuário vai informar seu nome e por fim, o computador vai imprimir na tela:
//    olá <nome informado pelo usuário>.
// Seção de Declarações
var
   nome_do_usuario: caracter
inicio
      escreva("informe o seu nome: ")
      leia(nome_do_usuario)
      escreva("olá " + nome_do_usuario)
fimalgoritmo
